name: Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint-and-build:
    name: Build/Lint/Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Lint
        run: npm run lint
      - name: Run Format Check
        run: npm run format:check
  playwright-tests:
    name: Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        id: playwright_tests
        run: npm run test:coverage
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-coverage
          path: coverage/playwright-coverage/
          retention-days: 30
  coverage-report:
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-tests, playwright-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Download playwright coverage
        uses: actions/download-artifact@v4
        with:
          name: playwright-coverage
          path: coverage/playwright-coverage/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JonasDutzi/ui5-sankey
