name: Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint-and-build:
    name: Build/Lint/Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Build
        run: pnpm run build
      - name: Run Lint
        run: pnpm run lint
      - name: Run Format Check
        run: pnpm run format:check
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Build
        run: pnpm run build
      - name: Run Unit Tests
        run: pnpm test:unit:coverage
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-coverage
          path: coverage/vitest-coverage/
          retention-days: 30
  playwright-tests:
    name: Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Run Playwright tests
        run: pnpm run test:playwright:coverage
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-coverage
          path: coverage/playwright-coverage/
          retention-days: 30
  coverage-report:
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-tests, playwright-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Download vitest coverage
        uses: actions/download-artifact@v4
        with:
          name: vitest-coverage
          path: coverage/vitest-coverage/
      - name: Download playwright coverage
        uses: actions/download-artifact@v4
        with:
          name: playwright-coverage
          path: coverage/playwright-coverage/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JonasDutzi/svelte-sankey
